// Character grid maps.  # wall  . floor  S start  E enemy  X exit  T torch  B barrel  P pillar
// C caster spawn  K charger spawn  h health pickup  a ammo pickup  Z boss spawn
// T/B/P/C/K/h/a are walkable (decoration/spawn only). Borders are walls; layouts are room + corridor.
export const CELL = 4;

export const MAPS = [
  {
    name: 'STAGE 1 — STONE HALLS', themeIndex: 0,
    enemyHp: 36, enemySpeed: 2.0, enemyDamage: 7,
    grid: [
      '################',
      '#S..T#....T....#',
      '#....#..####...#',
      '#....#..#E.#.B.#',
      '#.####..#..#...#',
      '#....T...P..T..#',
      '#.#####.####.###',
      '#..E..#....#..C#',
      '#..B..#.P..#...#',
      '#..h..T....T.Xa#',
      '################',
    ],
  },
  {
    name: 'STAGE 2 — HELL PIT', themeIndex: 1,
    enemyHp: 48, enemySpeed: 2.6, enemyDamage: 9,
    grid: [
      '################',
      '#S...T....E...T#',
      '#.####.##.####.#',
      '#.#B.....P...B.#',
      '#.#.####.####.##',
      '#..aT.C..E.T...#',
      '#.####.##.####.#',
      '#.#...B..P..C..#',
      '#.#.########.#.#',
      '#..T.h..E.K.T.X#',
      '################',
    ],
  },
  {
    name: 'STAGE 3 — STEEL CORE', themeIndex: 2,
    enemyHp: 60, enemySpeed: 3.1, enemyDamage: 11,
    grid: [
      '##################',
      '#S..T#..E..#..T..#',
      '#....#..C..#.....#',
      '#..P.#.####.#.P..#',
      '#....C.#B.#.K....#',
      '#.####.#..#.####.#',
      '#..T.h..PP..aT...#',
      '#.####.#..#.####.#',
      '#....K.#B.#.C....#',
      '#..P.#.####.#.P..#',
      '#....#..E..#..T..#',
      '#..T.h.......Xa..#',
      '##################',
    ],
  },
  {
    name: 'STAGE 4 — THE WARLORD', themeIndex: 1,
    enemyHp: 80, enemySpeed: 2.8, enemyDamage: 14,
    grid: [
      '####################',
      '#..................#',
      '#..T............T..#',
      '#..................#',
      '#....h......a......#',
      '#..................#',
      '#...T..........T...#',
      '#..................#',
      '#..P..........P....#',
      '#..................#',
      '#S.................#',
      '#..................#',
      '#...T..........T...#',
      '#..................#',
      '#....h......a......#',
      '#..................#',
      '#..................#',
      '#...T...Z.......X..#',
      '#..................#',
      '####################',
    ],
  },
];
